### ISSUE TITLE
`ignore_filetypes` no work with 'neo-tree'

### ISSUE THREAD

**Issue by Wansmer** [ja-ford/delaytrain.nvim#7]
Hi, thanks for nice plugin. 
When I set `neo-tree` to `ignore_filetypes` it still has disabled my j/k movements. I expected what this filetype will be ignored, but it not happens.
I checked filetype of neo-tree with `:lua =vim.bo.filetype` and it is `neo-tree`, no wrong filetype in config.

Also, when I set empty string to `ignore_filetypes` – after that plugin stop disabling movements with j/k in any other files. Not sure what it is an expected behavior :-)

**Comment by mauricekraus** [comment]
Hey @Wansmer,

the problem is not the implementation but the used string.match function. If we would use == everything would work fine, but by using match the hyphen holds a special meaning in Lua patterns. Therefore we need to escape the `-` with a `%`. Then everything should work fine. 

-> `neo%-tree`

@ja-ford This issue can be closed.
